# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-10 00:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(default='', max_length=100, verbose_name='major')),
                ('year', models.IntegerField(default=1, verbose_name='year')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='t_update')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='t_create')),
                ('basic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
